### ISSUE TITLE
web python debugger stuck 

### ISSUE THREAD

**Issue by bilalbayasut** [romanvm/python-web-pdb#11]
Hi firstly thanks for this useful tool. However I face a problem when I try to just continue the execution. When I look at my app , it is correct that the app is continued . But after that , when I want to quit the session, it just stuck or hang , and I reload the web debugger, it shows the same which is the last command I used which is `continue` . I could not do anything about it except to rerun container. How do I solve this ? thanks in advance

**Comment by romanvm** [comment]
Could you provide more details?
- Python version.
- Web-PDB version.
- Your browser.
- On what system are your running Web-PDB?

**Comment by bilalbayasut** [comment]
@romanvm thanks for your response

python 3.71
latest version of web-PDB
chrome
and I'm running it with flask based app run inside docker.

It is not like the normal debugger, I can use it but I have to restart my containers

**Comment by romanvm** [comment]
To be honest I've never tested web-pdb inside containers so I cannot tell anything about that.

**Comment by romanvm** [comment]
This may be fixed in #20. Please check.

**Comment by romanvm** [comment]
Closing this because of no further feedback.
