### ISSUE TITLE
Support for other debuggers

### ISSUE THREAD

**Issue by orwell1984** [romanvm/python-web-pdb#14]
Thanks for this awesome tool!

If I may suggest a feature - it would be cool to be able to use, say `pydbgr` under this.

**Comment by romanvm** [comment]
> pydbgr
Python 2 only support and hosting on Google Code kinda gives you a gentle hint that the project is long dead and rotted.

**Comment by orwell1984** [comment]
Yep, you are right. Didn't notice that.
