### ISSUE TITLE
C# + PythonNet use case

### ISSUE THREAD

**Issue by Martin-Molinero** [romanvm/python-web-pdb#17]
Hi, awesome repo! :)

I was testing `web-pdb` using C# + https://github.com/pythonnet/pythonnet , specifically calling Python from a C# process. Example: `PythonEngine.RunSimpleString("import web_pdb; web_pdb.set_trace()");`

My issue/feature request/advice request, is that `web-pdb` is closing when coming back from the Python code to the C# side, getting the `*** Thread finished ***` message from https://github.com/romanvm/python-web-pdb/blob/master/web_pdb/__init__.py#L166 `__init__.py:dispatch_return()`
and I'd like it to continue to live until the process ends or maybe the `WebPdb` instance is disposed/shutdown.

Thoughts?
Thanks!

**Comment by romanvm** [comment]
It makes absolutely no sense to run the webserver part of web-pdb after the interpreter exits the top-most execution frame of the code being taced. There is nothing to debug after that.

**Comment by Martin-Molinero** [comment]
The C# + PythonNet use case I'm facing is about embedding python in C#, so it's going back and forth multiple times from C# to Python, so the interpreter exits the top-most execution frame multiple times too.

**Comment by romanvm** [comment]
Long story short: you cannot share a debugger instance between different Python interpreter instances.

**Comment by Martin-Molinero** [comment]
I understand, but in this case, it will just be 1 interpreter instance, 1 initial call to `Py_Initialize()`.
I've tested just commenting out the `if` statement at https://github.com/romanvm/python-web-pdb/blob/master/web_pdb/__init__.py#L165 and it worked correctly, but it was just a hack so wanted to know your thoughts
