### ISSUE TITLE
Awesome

### ISSUE THREAD

**Issue by Aletz-Arce** [romanvm/python-web-pdb#22]
Hi @romanvm,
Thanks for this great tool, i'm used web-pdn inside docker container for my team.
It's very usefull, congratulations!!

**Comment by romanvm** [comment]
Thank you for your good words. I'll close the issue if you don't mind.

**Comment by Aletz-Arce** [comment]
> Thank you for your good words. I'll close the issue if you don't mind.

Of Course, 
I'm planning to write a post in Medium about this great tool, in my team i have junior python developers, this tools it's realy comfortable for success debuggin task with lower barrier entry.
Thank You
