### ISSUE TITLE
Spam Ajax GET requests to http://127.0.0.1:5555/output/update

### ISSUE THREAD

**Issue by alexington** [romanvm/python-web-pdb#3]
Hello! When I open the debugger in my browser and check the console I see that it's making repeated GET requests to `http://127.0.0.1:5555/output/update` in the background.  These fail with `403 (Forbidden)` since there's nothing in my application at that URL.

Is this normal?  Perhaps I've missed some configuration detail?  

I'm using Chrome Version 55.0.2883.95 (64-bit).  

Here is a screenshot of the console:

![image](https://cloud.githubusercontent.com/assets/5640879/21688200/e8ab2d6c-d339-11e6-9d20-3d00b1f439f0.png)

**Comment by romanvm** [comment]
Those are normal calls to Web-PDB back-end to update the web-console info.
