### ISSUE TITLE
I'm wondering if it's possible to use python-web-pdb with pytest

### ISSUE THREAD

**Issue by mmngreco** [romanvm/python-web-pdb#35]
Hi there!

I'm wondering if it's possible to use "python-web-pdb" as a pdb backend for pytest, something similar to [this SO question](https://stackoverflow.com/questions/39162569/use-ipdb-instead-of-pdb-with-py-test-pdb-option). If so, how I should fill `--pdbcls` ?

Thanks in advance!

**Comment by romanvm** [comment]
In theory it should be possible because `WebPdb` is a subclass of `Pdb`. You can try something like this: `--pdbcls=web_pdb:WebPdb`.

**Comment by romanvm** [comment]
Web-PDB is meant mostly for environments with no access to a terminal, let alone a full-featured GUI, so launching a web-browser does not make much sense. I'm closing this issue as solved.

**Comment by mmngreco** [comment]
Yeah, that makes sense. Thank you!
