### ISSUE TITLE
Unable to see source code

### ISSUE THREAD

**Issue by Dan-Eli** [romanvm/python-web-pdb#42]
I'm using web-db in the context of remote debug (on the same machine) with a tool call FME.  This tool is a GUI ETL (Extract Transform ans load) that manupulates spatial information.  In FME we can include python scripts to create specific manipulations that are not supplied by the basic GUI tools.  When I include a python script that is stored on the file disk system and referenced with 
`from aaa import bbb` there is no problem and I can debug and see my code/variable in the browser.  There is another mode in FME tool, where we can write directly  the python code which is not stored on the file disk system and we do not need to import it (the python code is probably loaded dynamically).  When I use the latter method, I can start web-pdb in the browser but I cannot see the python source code and neither the variables but I know web-pdb is working as I can print the content of the variable from the PDB window (at the bottom) and step blindly from line to line.  Is there something I'm doing wrongly, if not it would be very useful to adapt web-pdb for that context.

**Comment by romanvm** [comment]
I'm afraid this is a limitation of Python's built-in PDB. Web-PDB is only a front-end for PDB.
