### ISSUE TITLE
Remove '...' after address to cmd+click directly from VSCode

### ISSUE THREAD

**Issue by xLinkOut** [romanvm/python-web-pdb#51]
Not a big deal but trying to CMD+Click, from Visual Studio Code terminal, on the `hostname:port` when pdb start doesn't directly open the browser but open the VSC popup window saying 'No matching results', as the three dots are recognised as part of the input.

Adding a space in between or deleting them should solve the issue, and it could improve the workflow.

![immagine](https://user-images.githubusercontent.com/14892153/174761173-347d79f9-a863-46fa-b7f4-cfa3132d110b.png)

Apart from that, your `web-pdb` has already saved me a looot of time! Thank you!

**Comment by clach04** [comment]
First thing I encountered too (but in console window), I was hoping to be lazy and double click on URL. As of 2023-03-12 that's not possible for a couple of reasons:

1. no protocol
2. `...` on end also included in "copy"

    diff --git a/web_pdb/web_console.py b/web_pdb/web_console.py
    index 75f65c8..e7d8e3f 100644
    --- a/web_pdb/web_console.py
    +++ b/web_pdb/web_console.py
    @@ -103,7 +103,7 @@ class WebConsole:
             self._server_thread = Thread(target=self._run_server, args=(host, port))
             self._server_thread.daemon = True
             logging.critical(
    -            'Web-PDB: starting web-server on %s:%s...', gethostname(), port)
    +            'Web-PDB: starting web-server on http://%s:%s ...', gethostname(), port)
             self._server_thread.start()

         @property

I was also hoping I could click on a link in the readme to, say, http://localhost:5555 (assuming the default). I'll follow up with questions on https://github.com/romanvm/python-web-pdb/pull/54

**Comment by clach04** [comment]
https://github.com/clach04/python-web-pdb/tree/issue51_easy_copy_paste_url_with_protocol_readme#usage has a quick hack to the readme for lazy people like me ;-)

**Comment by romanvm** [comment]
done

**Comment by clach04** [comment]
@romanvm Thanks for committing https://github.com/romanvm/python-web-pdb/commit/b7b3a412ca988ad655f56db80fdea96674c88da2 and for this great debugger!
