### ISSUE TITLE
Server stops/quit 

### ISSUE THREAD

**Issue by gtalarico** [romanvm/python-web-pdb#6]
I am trying to runa simple set_trace, but it keeps quiting automatically after starting.\
Any ideas what I can try?
```
Python 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:19:22) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import web_pdb; web_pdb.set_trace()
Web-PDB: starting web-server on STUDIO-SSD:5555...
Web-PDB: stopping web-server...
Web-PDB: web-server stopped.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\gtalarico\AppData\Local\Programs\Python\Python27\Lib\bdb.py", line 53, in trace_dispatch
    return self.dispatch_return(frame, arg)
  File "web_pdb\__init__.py", line 112, in dispatch_return
    return Pdb.dispatch_return(self, frame, arg)
  File "C:\Users\gtalarico\AppData\Local\Programs\Python\Python27\Lib\bdb.py", line 91, in dispatch_return
    if self.quitting: raise BdbQuit
bdb.BdbQuit
```

**Comment by romanvm** [comment]
First, PDB debugger is not meant to be run in an interactive session. Second, `BdbQuit` exception is thrown when you terminate a debugging session with `q` command. This is how PDB works. Web-PDB is simply a web-UI for PDB, it does not change the way how PDF works.

**Comment by gtalarico** [comment]
> PDB debugger is not meant to be run in an interactive session
I agree, but  standard pdb does runs ok on interactive. It was just a quick way to test it
In any case, I also tried calling it from a file, and got the same result.

> BdbQuit exception is thrown when you terminate a debugging session with q command
Yes! I use the standard pdb often. This is happening without me pressing anything

![console pdb](https://user-images.githubusercontent.com/9513968/29373665-f7726f52-827c-11e7-82a1-eb73448d65b2.gif)

But's all good, I was just trying to see how it worked. Thanks

**Comment by gtalarico** [comment]
Got it to work. 
it fails if set_trace is called from an empty file

![image](https://user-images.githubusercontent.com/9513968/29374086-395ff6a4-827e-11e7-824d-749dffae18ba.png)

![image](https://user-images.githubusercontent.com/9513968/29374105-4a962876-827e-11e7-86f8-aabefb9c0c07.png)

**Comment by romanvm** [comment]
I've been able to reproduce the issue so I'll investigate it when I have some free time.
