### ISSUE TITLE
Trying to use it with Odoo but no results. 

### ISSUE THREAD

**Issue by piqoni** [romanvm/python-web-pdb#7]
Very exciting library! I'm trying to use it with Odoo but port 5555 outputs connection refused. 
Maybe I'm missing something? Or if you have any advice, would be appreciated.

**Comment by romanvm** [comment]
I have no idea what "Odoo" is, but general advice is to check your firewall settings and/or try a different port.

**Comment by piqoni** [comment]
Just fixed it, it was environmental issue. Thanks a lot for responding. Though, when I click `continue execution` the next time I pass the breakpoint it throws:
```
  File "/usr/lib/python2.7/bdb.py", line 49, in trace_dispatch
    return self.dispatch_line(frame)
  File "/usr/lib/python2.7/bdb.py", line 68, in dispatch_line
    if self.quitting: raise BdbQuit
BdbQuit
```

Thanks for the library!

**Comment by romanvm** [comment]
Please provide as much details as possible to reproduce your problem. Also, there's a known bug when `BdbQuit` is thrown when `set_trace()` is put on the very last line of a `.py` file.

**Comment by piqoni** [comment]
My app ([Odoo](https://hub.docker.com/_/odoo/)) is in a docker container. Host OS is Windows. Not sure how can you reproduce easily. :(
And no, in my case the set_trace() is not at the end of .py file.

**Comment by romanvm** [comment]
Unfortunately, without being able to reproduce the issue I cannot help you much.
